// Renderer element-domain helpers split the page-wide DOM registry into
// crawler, organizer, subscription, and shell segments. This keeps the main
// element collector readable and makes future per-module element cleanup less
// error-prone.
//
// Ownership summary:
// 1) define per-workspace DOM lookup ownership
// 2) keep page-wide element collection segmented by domain
// 3) avoid letting controllers hand-maintain scattered getElementById calls
//
// File map for maintainers:
// 1) shell element ownership
// 2) crawler element ownership
// 3) organizer/subscription element ownership
(function initializeRendererElementDomains(globalScope) {
  // Shell nodes are the only DOM handles shared across workspaces. Keep this
  // list limited to navigation and top-level container ownership.
  function collectShellElements(scope) {
    return {
      navCrawlerButton: scope.getElementById('nav-crawler'),
      navOrganizerButton: scope.getElementById('nav-organizer'),
      navSubscriptionButton: scope.getElementById('nav-subscription'),
      navLibraryMetadataButton: scope.getElementById('nav-librarymetadata'),
      crawlerWorkspace: scope.getElementById('crawler-workspace'),
      organizerWorkspace: scope.getElementById('organizer-workspace'),
      subscriptionWorkspace: scope.getElementById('subscription-workspace'),
      libraryMetadataWorkspace: scope.getElementById('librarymetadata-workspace')
    };
  }

  // Crawler/organizer/subscription collectors should contain only DOM lookup
  // ownership, not fallback logic. Controllers may decide how to behave when a
  // node is absent, but this file should stay a pure registry.
  function collectCrawlerElements(scope) {
    return {
      base: scope.getElementById('base'),
      output: scope.getElementById('output'),
      limit: scope.getElementById('limit'),
      totalPages: scope.getElementById('totalPages'),
      itemsPerPage: scope.getElementById('itemsPerPage'),
      parallel: scope.getElementById('parallel'),
      delay: scope.getElementById('delay'),
      timeout: scope.getElementById('timeout'),
      proxy: scope.getElementById('proxy'),
      proxyStatus: scope.getElementById('proxy-status'),
      proxyStatusDetail: scope.getElementById('proxy-status-detail'),
      magnetExcludeKeywords: scope.getElementById('magnetExcludeKeywords'),
      minReleaseDate: scope.getElementById('minReleaseDate'),
      actressCountFilterThreshold: scope.getElementById('actressCountFilterThreshold'),
      filmCodeFilterThreshold: scope.getElementById('filmCodeFilterThreshold'),
      taskTemplate: scope.getElementById('taskTemplate'),
      cloudflare: scope.getElementById('cloudflare'),
      secondValidation: scope.getElementById('secondValidation'),
      nomag: scope.getElementById('nomag'),
      allmag: scope.getElementById('allmag'),
      magnetContentValidation: scope.getElementById('magnetContentValidation'),
      metadataOnly: scope.getElementById('metadataOnly'),
      nopic: scope.getElementById('nopic'),
      startButton: scope.getElementById('start'),
      stopButton: scope.getElementById('stop'),
      restartButton: scope.getElementById('restart'),
      chooseBackgroundButton: scope.getElementById('choose-background'),
      resetBackgroundButton: scope.getElementById('reset-background'),
      browseOutputButton: scope.getElementById('browse-output'),
      openOutputButton: scope.getElementById('open-output'),
      openMagnetFileButton: scope.getElementById('open-magnet-file'),
      openLogFolderButton: scope.getElementById('open-log-folder'),
      openLogOutputButton: scope.getElementById('open-log-output'),
      openLogMagnetButton: scope.getElementById('open-log-magnet'),
      updateAntiBlockButton: scope.getElementById('update-antiblock'),
      clearLogButton: scope.getElementById('clear-log'),
      useSuggestedPagesButton: scope.getElementById('use-suggested-pages'),
      statusPill: scope.getElementById('status-pill'),
      stateMessage: scope.getElementById('state-message'),
      currentBox: scope.getElementById('current-box'),
      currentTotalView: scope.getElementById('current-total'),
      currentItemsView: scope.getElementById('current-items'),
      unfinishedBox: scope.getElementById('unfinished-box'),
      unfinishedItemsView: scope.getElementById('unfinished-items'),
      unfinishedTotalView: scope.getElementById('unfinished-total'),
      duplicateBox: scope.getElementById('duplicate-box'),
      duplicateItemsView: scope.getElementById('duplicate-items'),
      duplicateTotalView: scope.getElementById('duplicate-total'),
      pageGapBox: scope.getElementById('page-gap-box'),
      pageGapItemsView: scope.getElementById('page-gap-items'),
      failedBox: scope.getElementById('failed-box'),
      failedTotalView: scope.getElementById('failed-total'),
      failedItemsView: scope.getElementById('failed-items'),
      filteredBox: scope.getElementById('filtered-box'),
      filteredItemsView: scope.getElementById('filtered-items'),
      filteredTotalView: scope.getElementById('filtered-total'),
      completedBox: scope.getElementById('completed-box'),
      completedItemsView: scope.getElementById('completed-items'),
      completedTotalView: scope.getElementById('completed-total'),
      crawlStageStatus: scope.getElementById('crawl-stage-status'),
      crawlStageProgress: scope.getElementById('crawl-stage-progress'),
      crawlStageTitle: scope.getElementById('crawl-stage-title'),
      crawlStageDescription: scope.getElementById('crawl-stage-description'),
      crawlStageMessage: scope.getElementById('crawl-stage-message'),
      crawlStageBarFill: scope.getElementById('crawl-stage-bar-fill'),
      crawlStageBar: scope.getElementById('crawl-stage-bar'),
      crawlStageOutput: scope.getElementById('crawl-stage-output'),
      crawlStagePage: scope.getElementById('crawl-stage-page'),
      crawlStageQueued: scope.getElementById('crawl-stage-queued'),
      crawlStageAttempted: scope.getElementById('crawl-stage-attempted'),
      crawlStageCompleted: scope.getElementById('crawl-stage-completed'),
      crawlResultQuality: scope.getElementById('crawl-result-quality'),
      crawlResultSummary: scope.getElementById('crawl-result-summary'),
      crawlResultHistoryView: scope.getElementById('crawl-result-history'),
      crawlClearHistoryButton: scope.getElementById('crawl-clear-history'),
      logView: scope.getElementById('log-view'),
      logFilePath: scope.getElementById('log-file-path'),
      statPage: scope.getElementById('stat-page'),
      statQueued: scope.getElementById('stat-queued'),
      statAttempted: scope.getElementById('stat-attempted'),
      statCompleted: scope.getElementById('stat-completed'),
      totalPagesAdvice: scope.getElementById('total-pages-advice'),
      totalPagesMeta: scope.getElementById('total-pages-meta'),
      baseUrlHints: scope.getElementById('base-url-hints'),
      sourceLink: scope.getElementById('source-link'),
      rankingMode: scope.getElementById('ranking-mode'),
      rankingSourceChannel: scope.getElementById('ranking-source-channel'),
      rankingYear: scope.getElementById('ranking-year'),
      rankingYearField: scope.getElementById('ranking-year-field'),
      rankingMonth: scope.getElementById('ranking-month'),
      rankingMonthField: scope.getElementById('ranking-month-field'),
      rankingHelp: scope.getElementById('ranking-help'),
      rankingChannelTip: scope.getElementById('ranking-channel-tip'),
      rankingMeta: scope.getElementById('ranking-meta'),
      rankingSource: scope.getElementById('ranking-source'),
      rankingSourceText: scope.getElementById('ranking-source-text'),
      openRankingSourceButton: scope.getElementById('open-ranking-source'),
      refreshRankingButton: scope.getElementById('refresh-ranking'),
      rankingView: scope.getElementById('ranking-view'),
      crawlCacheSelect: scope.getElementById('crawl-cache-select'),
      crawlCacheRefreshButton: scope.getElementById('crawl-cache-refresh'),
      crawlCacheRemoveButton: scope.getElementById('crawl-cache-remove'),
      crawlCacheClearButton: scope.getElementById('crawl-cache-clear'),
      crawlCacheSummary: scope.getElementById('crawl-cache-summary')
    };
  }

  function collectOrganizerElements(scope) {
    // Organizer lookups stay grouped so future organizer-only UI cleanup can
    // happen without reopening crawler or subscription controllers.
    return {
      organizerRoot: scope.getElementById('organizer-root'),
      organizerBrowseRootButton: scope.getElementById('organizer-browse-root'),
      organizerCrawlOutput: scope.getElementById('organizer-crawl-output'),
      organizerUseLatestOutputButton: scope.getElementById('organizer-use-latest-output'),
      organizerLoadCodesButton: scope.getElementById('organizer-load-codes'),
      organizerDiscoverCodesButton: scope.getElementById('organizer-discover-codes'),
      organizerCodeSource: scope.getElementById('organizer-code-source'),
      organizerCodeCount: scope.getElementById('organizer-code-count'),
      organizerMinSize: scope.getElementById('organizer-min-size'),
      organizerSuffix: scope.getElementById('organizer-suffix'),
      organizerVideoExtensions: scope.getElementById('organizer-video-extensions'),
      organizerAdFileActionMove: scope.getElementById('organizer-ad-file-action-move'),
      organizerAdFileActionDelete: scope.getElementById('organizer-ad-file-action-delete'),
      organizerBatchDelete: scope.getElementById('organizer-batch-delete'),
      organizerRateLimitGrid: scope.getElementById('organizer-rate-limit-grid'),
      organizerDeleteInterval: scope.getElementById('organizer-delete-interval'),
      organizerOrganizeInterval: scope.getElementById('organizer-organize-interval'),
      organizerDryRun: scope.getElementById('organizer-dry-run'),
      organizerIncludeSubdirectories: scope.getElementById('organizer-include-subdirectories'),
      organizerStrictCodeMatch: scope.getElementById('organizer-strict-code-match'),
      organizerRetryMissingMagnets: scope.getElementById('organizer-retry-missing-magnets'),
      organizerAdDetectionEnabled: scope.getElementById('organizer-ad-detection-enabled'),
      organizerAdDetectionEnable: scope.getElementById('organizer-ad-detection-enable'),
      organizerAdDetectionDisable: scope.getElementById('organizer-ad-detection-disable'),
      organizerAdModelType: scope.getElementById('organizer-ad-model-type'),
      organizerAdThreshold: scope.getElementById('organizer-ad-threshold'),
      organizerAdKeywords: scope.getElementById('organizer-ad-keywords'),
      organizerLearningCodes: scope.getElementById('organizer-learning-codes'),
      organizerImportAdSamplesButton: scope.getElementById('organizer-import-ad-samples'),
      organizerHelpImportAdButton: scope.getElementById('organizer-help-import-ad'),
      organizerImportNormalSamplesButton: scope.getElementById('organizer-import-normal-samples'),
      organizerHelpImportNormalButton: scope.getElementById('organizer-help-import-normal'),
      organizerLearnAdByCodesButton: scope.getElementById('organizer-learn-ad-by-codes'),
      organizerHelpLearnAdButton: scope.getElementById('organizer-help-learn-ad'),
      organizerLearnNormalByCodesButton: scope.getElementById('organizer-learn-normal-by-codes'),
      organizerHelpLearnNormalButton: scope.getElementById('organizer-help-learn-normal'),
      organizerRefreshLearningSummaryButton: scope.getElementById('organizer-refresh-learning-summary'),
      organizerLearningSummary: scope.getElementById('organizer-learning-summary'),
      organizerDependencySummary: scope.getElementById('organizer-dependency-summary'),
      organizerDependencyDetail: scope.getElementById('organizer-dependency-detail'),
      organizerRefreshDependencyButton: scope.getElementById('organizer-refresh-dependency'),
      organizerInstallFfmpegButton: scope.getElementById('organizer-install-ffmpeg'),
      organizerInstallOnnxButton: scope.getElementById('organizer-install-onnx'),
      organizerDeleteDependencyButton: scope.getElementById('organizer-delete-dependency'),
      organizerFfmpegDownloadUrl: scope.getElementById('organizer-ffmpeg-download-url'),
      organizerOnnxDownloadUrl: scope.getElementById('organizer-onnx-download-url'),
      organizerAlistUrl: scope.getElementById('organizer-alist-url'),
      organizerStartButton: scope.getElementById('organizer-start'),
      organizerPreviewButton: scope.getElementById('organizer-preview'),
      organizerRescueNamesButton: scope.getElementById('organizer-rescue-names'),
      organizerOpenWaitingButton: scope.getElementById('organizer-open-waiting'),
      organizerOpenOrganizedButton: scope.getElementById('organizer-open-organized'),
      organizerOpenUnmatchedButton: scope.getElementById('organizer-open-unmatched'),
      organizerOpenDeleteButton: scope.getElementById('organizer-open-delete'),
      organizerClearLogButton: scope.getElementById('organizer-clear-log'),
      organizerStatusPill: scope.getElementById('organizer-status-pill'),
      organizerScanned: scope.getElementById('organizer-stat-scanned'),
      organizerVideoTotal: scope.getElementById('organizer-stat-video'),
      organizerMatched: scope.getElementById('organizer-stat-matched'),
      organizerMovedUnmatched: scope.getElementById('organizer-stat-unmatched'),
      organizerMovedDelete: scope.getElementById('organizer-stat-delete'),
      organizerFailed: scope.getElementById('organizer-stat-failed'),
      organizerSummaryMessage: scope.getElementById('organizer-summary-message'),
      organizerHeroSubtitle: scope.querySelector('#organizer-hero .hero-subtitle'),
      organizerHeroTip: scope.querySelector('#organizer-hero .hero-tip'),
      organizerLogView: scope.getElementById('organizer-log-view')
    };
  }

  function collectSubscriptionElements(scope) {
    // Subscription nodes are intentionally isolated from crawler lookups even
    // when they may later reuse shared artifact concepts. Keep the DOM contract
    // independent so page changes do not silently couple the workspaces again.
    return {
      subscriptionOutput: scope.getElementById('subscription-output'),
      subscriptionUseLatestOutputButton: scope.getElementById('subscription-use-latest-output'),
      subscriptionScanButton: scope.getElementById('subscription-scan-output'),
      subscriptionActressName: scope.getElementById('subscription-actress-name'),
      subscriptionTargetUrl: scope.getElementById('subscription-target-url'),
      subscriptionSyncedCount: scope.getElementById('subscription-synced-count'),
      subscriptionItemsPerPage: scope.getElementById('subscription-items-per-page'),
      subscriptionTotalPages: scope.getElementById('subscription-total-pages'),
      subscriptionAddButton: scope.getElementById('subscription-add'),
      subscriptionRefreshButton: scope.getElementById('subscription-refresh'),
      subscriptionClearAllButton: scope.getElementById('subscription-clear-all'),
      subscriptionClearFormButton: scope.getElementById('subscription-clear-form'),
      subscriptionRecentCrawlSelect: scope.getElementById('subscription-recent-crawl-select'),
      subscriptionUseRecentCrawlButton: scope.getElementById('subscription-use-recent-crawl'),
      subscriptionImportRecentButton: scope.getElementById('subscription-import-recent'),
      subscriptionDetectAllButton: scope.getElementById('subscription-detect-all'),
      subscriptionManualImportButton: scope.getElementById('subscription-import-manual-json'),
      subscriptionManualJsonInput: scope.getElementById('subscription-manual-json-input'),
      subscriptionManualCreateButton: scope.getElementById('subscription-create-manual'),
      subscriptionUseSeedButton: scope.getElementById('subscription-use-seed'),
      subscriptionDetailCard: scope.getElementById('subscription-detail-card'),
      subscriptionDetailEmpty: scope.getElementById('subscription-detail-empty'),
      subscriptionStatTotal: scope.getElementById('subscription-stat-total'),
      subscriptionStatUpdated: scope.getElementById('subscription-stat-updated'),
      subscriptionStatPending: scope.getElementById('subscription-stat-pending'),
      subscriptionStatChecked: scope.getElementById('subscription-stat-checked'),
      subscriptionStatTotalSide: scope.getElementById('subscription-stat-total-side'),
      subscriptionStatUpdatedSide: scope.getElementById('subscription-stat-updated-side'),
      subscriptionStatCheckedSide: scope.getElementById('subscription-stat-checked-side'),
      subscriptionSummaryMessage: scope.getElementById('subscription-summary-message'),
      subscriptionHeroCopy: scope.querySelector('#subscription-workspace .hero-copy'),
      subscriptionList: scope.getElementById('subscription-list'),
      subscriptionLogView: scope.getElementById('subscription-log-view'),
      subscriptionCrawlerStatus: scope.getElementById('subscription-crawler-status'),
      subscriptionProxyStatus: scope.getElementById('subscription-proxy-status'),
      subscriptionProxyStatusDetail: scope.getElementById('subscription-proxy-status-detail'),
      subscriptionCrawlerUrl: scope.getElementById('subscription-crawler-url'),
      subscriptionCrawlerCount: scope.getElementById('subscription-crawler-count'),
      subscriptionCrawlerActressName: scope.getElementById('subscription-crawler-actress-name'),
      subscriptionCrawlerParallel: scope.getElementById('subscription-crawler-parallel'),
      subscriptionCrawlerDelay: scope.getElementById('subscription-crawler-delay'),
      subscriptionCrawlerTimeout: scope.getElementById('subscription-crawler-timeout'),
      subscriptionCrawlerProxy: scope.getElementById('subscription-crawler-proxy'),
      subscriptionCrawlerCloudflare: scope.getElementById('subscription-crawler-cloudflare'),
      subscriptionUpdateAntiBlockButton: scope.getElementById('subscription-update-antiblock'),
      subscriptionStartCrawlButton: scope.getElementById('subscription-start-crawl'),
      subscriptionBatchCrawlButton: scope.getElementById('subscription-batch-crawl'),
      subscriptionBatchDialog: scope.getElementById('subscription-batch-dialog'),
      subscriptionBatchConcurrency: scope.getElementById('subscription-batch-concurrency'),
      subscriptionBatchConfirmButton: scope.getElementById('subscription-batch-confirm'),
      subscriptionBatchCancelButton: scope.getElementById('subscription-batch-cancel'),
      subscriptionStopCrawlButton: scope.getElementById('subscription-stop-crawl'),
      subscriptionOpenOutputButton: scope.getElementById('subscription-open-output'),
      subscriptionOpenFolderButton: scope.getElementById('subscription-open-folder')
    };
  }

  function collectLibraryMetadataElements(scope) {
    // Library metadata (media library scraping) nodes are kept isolated so the
    // controller can own its own DOM contract without scattering lookups.
    return {
      libraryMetadataLayout: scope.getElementById('librarymetadataLayout'),
      libraryRootPath: scope.getElementById('libraryRootPath'),
      browseLibraryRootButton: scope.getElementById('browseLibraryRoot'),
      libraryOutputMode: scope.getElementById('libraryOutputMode'),
      crawlArtifactPath: scope.getElementById('crawlArtifactPath'),
      crawlArtifactCountFeedback: scope.getElementById('crawlArtifactCountFeedback'),
      crawlArtifactCountBadge: scope.getElementById('crawlArtifactCountBadge'),
      browseCrawlArtifactsButton: scope.getElementById('browseCrawlArtifacts'),
      crawlSourceSnapshot: scope.getElementById('crawlSourceSnapshot'),
      refreshCrawlSourcesButton: scope.getElementById('refreshCrawlSources'),
      crawlFallbackInput: scope.getElementById('crawlFallbackInput'),
      rehydrateCodeButton: scope.getElementById('rehydrateCode'),
      testScrapeButton: scope.getElementById('testScrape'),
      scanFileTypes: scope.getElementById('scanFileTypes'),
      metadataSourcePriority: scope.getElementById('metadataSourcePriority'),
      libraryScrapeConcurrency: scope.getElementById('libraryScrapeConcurrency'),
      libraryAutoSubscribeLeadActor: scope.getElementById('libraryAutoSubscribeLeadActor'),
      libraryProxyUrl: scope.getElementById('libraryProxyUrl'),
      libraryProxyStatus: scope.getElementById('libraryProxyStatus'),
      libraryProxyStatusDetail: scope.getElementById('libraryProxyStatusDetail'),
      hiddenArtifactPath: scope.getElementById('hiddenArtifactPath'),
      browseHiddenArtifactsButton: scope.getElementById('browseHiddenArtifacts'),
      showHiddenFilesCheckbox: scope.getElementById('showHiddenFiles'),
      scanLibraryButton: scope.getElementById('scanLibrary'),
      filterCompleteButton: scope.getElementById('filterComplete'),
      filterMissingButton: scope.getElementById('filterMissing'),
      exportIndexButton: scope.getElementById('exportIndex'),
      libraryResultList: scope.getElementById('libraryResultList'),
      toggleLibraryResultScopeButton: scope.getElementById('toggleLibraryResultScope'),
      libraryStatusPill: scope.getElementById('library-status-pill'),
      libraryProgressPill: scope.getElementById('library-progress-pill'),
      openLibraryLogButton: scope.getElementById('openLibraryLog'),
      libraryLogView: scope.getElementById('libraryLogView'),
      scrapeSelectedButton: scope.getElementById('scrapeSelected'),
      scanAndScrapeAllButton: scope.getElementById('scanAndScrapeAll'),
      generateNfoOnlyButton: scope.getElementById('generateNfoOnly'),
      downloadImagesOnlyButton: scope.getElementById('downloadImagesOnly'),
      scrapeUnfinishedButton: scope.getElementById('scrapeUnfinished'),
      stopLibraryScrapeButton: scope.getElementById('stopLibraryScrape'),
      toggleLibraryLayoutButton: scope.getElementById('toggleLibraryLayout')
    };
  }

  globalScope.desktopRendererElementDomains = {
    collectCrawlerElements,
    collectOrganizerElements,
    collectShellElements,
    collectSubscriptionElements,
    collectLibraryMetadataElements
  };
})(typeof globalThis !== 'undefined' ? globalThis : window);
